#!/bin/sh


export HOST=https://192.168.1.50

PROG=`basename $0`
usage() {
    echo "Usage: $PROG --enable-all | --disable-all"
    exit 0
}

set_repl() {
    ID=$1
    REPL_TO=$2
    if http --check-status -pHBhb --verify=no --ignore-stdin PUT $HOST/api/v1.0/storage/replication/$ID/ repl_enabled=$REPL_TO
    then
            echo 'OK!'
    else
            case $? in
                2) echo 'Request timed out!' ;;
                3) echo 'Unexpected HTTP 3xx Redirection!' ;;
                4) echo 'HTTP 4xx Client Error!' ;;
                5) echo 'HTTP 5xx Server Error!' ;;
                6) echo 'Exceeded --max-redirects=<n> redirects!' ;;
                *) echo 'Other Error!' ;;
                    esac
    fi
}

for arg
do
    case "$arg" in
        --enable-all)
            REPL_FROM=false
            REPL_TO=true
            REPL_ACTION=enabling
            ;;
        --disable-all)
            REPL_FROM=true
            REPL_TO=false
            REPL_ACTION=disabling
            ;;
        *)
            usage
            ;;
    esac
done

test -n "$REPL_FROM" -a -n "$REPL_TO" || usage

http --verify=no $HOST/api/v1.0/storage/replication/                                |
        jq "map(select(.repl_enabled==$REPL_FROM)) | .[] | .id,.repl_filesystem"    |
        paste -d, - -                                                               |
        while read task
        do
            export ID=`echo $task | cut -d, -f1`
            NAME=`echo $task | cut -d, -f2`
            echo "$REPL_ACTION" $NAME
            set_repl $ID $REPL_TO
        done
